apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-gw-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - irori235.dev
  secretName: main-gw-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-gw-gke-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - gke.irori235.dev
  secretName: main-gw-gke-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-gw-gke-wildcard-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - "*.gke.irori235.dev"
  secretName: main-gw-gke-wildcard-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-gw-apps-wildcard-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - "*.apps.irori235.dev"
  secretName: main-gw-apps-wildcard-tls
