apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iap-external-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secret-store
  target:
    name: gke-iap-secret
    creationPolicy: Owner
  data:
    - secretKey: gke-iap-secret
      remoteRef:
        key: gke-iap-secret
        version: latest
