apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-iap-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - hosts:
        - iap.gke.irori235.dev
      secretName: nginx-iap-tls
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-iap-backendconfig
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: gke-iap-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-iap-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - iap.gke.irori235.dev
  secretName: nginx-iap-tls
