apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    g, irori-cluster-maintainer-gp:admin, role:admin
  scopes: "[groups]"
