apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-http
spec:
  parentRefs:
    - kind: Gateway
      name: main-gw
      namespace: gateway
  hostnames:
    - cd.gke.irori235.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
