apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-core
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: ">=1.20.0"
    helm:
      releaseName: istio-gateway-core
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
