apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: kmnz-healthcheck
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080 # containerPort
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: namakemono

---
apiVersion: v1
kind: Service
metadata:
  name: namakemono
spec:
  selector:
    app: namakemono
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namakemono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namakemono
  template:
    metadata:
      labels:
        app: namakemono
    spec:
      containers:
        - name: namakemono
          image: ghcr.io/cs-sysimpl/namakemono-manager:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: namakemono-db
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: app
            - name: DB_USER
              value: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kmnz-mysql-password
                  key: kmnz-mysql-password
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /healthz
