apiVersion: v1
kind: Service
metadata:
  name: namakemono-db
spec:
  selector:
    db: namakemono
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kmnz-mysql-pvc
  labels:
    app: kmnz-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namakemono-db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: namakemono
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        db: namakemono
    spec:
      containers:
        - name: mysql
          image: ghcr.io/cs-sysimpl/namakemono-manager-db:latest
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - name: tcp-mysql
              containerPort: 3306
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kmnz-mysql-password
                  key: kmnz-mysql-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  exec mysql -uuser -p${MYSQL_PASSWORD} -e "SELECT 1"
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: kmnz-mysql-pvc
