apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-gw-tls
spec:
  issuerRef:
    name: letsencrypt-stg
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - irori235.dev
  secretName: main-gw-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-gw-wildcard-tls
spec:
  issuerRef:
    name: letsencrypt-stg
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - gke.irori235.dev
  secretName: main-gw-wildcard-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-gw-wildcard-tls
spec:
  issuerRef:
    name: letsencrypt-stg
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - "*.gke.irori235.dev"
  secretName: main-gw-wildcard-tls
