apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cert-manager
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secret-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: cloudflare-api-token
        version: latest
